### PR TITLE
Update dependency versions.

### PR DESCRIPTION
**Pull request by azriel91**
Heya, recently `erased-serde` released `0.4`, and this library needs to pick up that change to work with that version.

I've also run `cargo fix --all`, and `cargo test --all` and everything appears to work fine.

If all's well, please could you also release a new version with this change?

Thank you :bowing_man:!

### CODE REVIEW

**Comment by qzed** [comment]
Thanks! I'll have a look at this later this evening.

That being said, I'm not actively developing/using this any more and I think there's also now https://github.com/dtolnay/typetag, which seems to offer the same functionality. Unless there's some functionality here that `typetag` doesn't provide, I think it might be better to retire this crate. So feel free to check that out and let me know. I'd probably still update it before archiving though.

**Comment by azriel91** [comment]
Heya, cool thanks; I checked out `typetag`, and:

* functionally `typetag` should work (my use case is downcasting, which is [supported](https://github.com/dtolnay/typetag/issues/10))

    Caveat: `typetag` needs the crate that defines the type to include the `#[typetag::serde]` attribute, which is a slight ergonomic loss in my larger project. With `serde_tagged`, my project takes in the type as a type parameter and does the registration for the consumer.

* `typetag`'s registration isn't currently supported on WASM ([yet](https://github.com/dtolnay/typetag/issues/54)), so deserialization is unable to find the type to deserialize.

    With `serde_tagged`, deserialization is supported -- see the `diff` button on [this page](https://peace.mk/book/examples/download.html), which deserializes the `status` and `goal` types before diffing them.

I couldn't find a supported way to manually register types -- which would address both the above issues -- besides copying [what the proc macro generates](https://github.com/dtolnay/typetag/blob/0.2.14/impl/src/tagged_impl.rs#L35), which feels a bit hacky.

Long spiel aside, if you're happy to provide myself access to both the repo / crates.io, I'm happy to maintain this crate to keep dependencies up to date / keep it building as Rust evolves.

peace :v:

**Comment by qzed** [comment]
Alright, sure. Those seem good reasons to keep it around.

Your PR looks good to me. I'll merge your PR, fix up some clippy warnings, and give you access to this repo and the crate.

**Comment by qzed** [comment]
Warnings are fixed in 10715c5fcb4cb2fdca7a29afce055b0f603b1e48. Feel free to push a new version (or make any further changes).

**Comment by qzed** [comment]
And of course: Thanks for the PR and taking up the work!

**Comment by azriel91** [comment]
Thank you very much :bowing_man:!

**Pull request merged**
